### ISSUE TITLE
ToArray1D: useful?

### ISSUE THREAD

**Issue by fmarionpoll** [Apollo3zehn/HDF5.NET#13]
Hi,
I am new to C# (but practicing Java, C++ for image analysis and electrophysiology) and I am trying to read H5 files storing recordings from 1024 micro-electrodes. These data are stored within an array of "int" with 1028 channels x many points (for ex 300,000) corresponding to the duration of the observation (data are sampled at 20 kHz)). 
I would like to extract 1 channel at a time from this array using the hyperslabs approach.

It looks to me that it would be useful to add a ToArray1D as follow:

public static unsafe T[] ToArray1D<T>(this T[] data, long dim0)
            where T : unmanaged
        {
            var dims = new long[] { dim0 };
            ArrayExtensions.ValidateInputData(data, dims);
            var output = new T[dims[0]];
            fixed (void* ptr = output)
            {
                ArrayExtensions.CopyData(data, ptr);
            }
            return output;
        }

Is there any other way to do this? Right now, I resolved to use ToArray2D but it seems awkward.

Thank you for any help,

Frederic

PS By the way, for a beginner like me, HDF5.NET is the most understandable library and it makes it easy to read all other fields in the H5 file I am working on. Thumbs up for your work!

**Comment by Apollo3zehn** [comment]
Hi Frederic,

I am glad that HDF5.NET is useful to you. I will continue to work on it later this year towards a v1 release.

Did you already try the built-in hyperslab functionality as described here (https://github.com/Apollo3zehn/HDF5.NET#4-partial-io-and-hyperslabs)?

Maybe something like this would work (untested):

var rows = 1024
var cols = 300_000;
var dataset = root.Dataset("myDataset");

for (int row = 0; i < rows; i++)
{
    var datasetSelection = new HyperslabSelection(start: row * cols, block: cols)
    var result = dataset.Read<int>(fileSelection: datasetSelection)
}

The array dimensions are part of the dataset variable. You can access them via dataset.Space.Dimensions.

Best regards,
Vincent

________________________________
Von: Frederic Marion-Poll ***@***.***>
Gesendet: Dienstag, 17. August 2021 23:36
An: Apollo3zehn/HDF5.NET ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Apollo3zehn/HDF5.NET] ToArray1D: useful? (#13)


Hi,
I am new to C# (but practicing Java, C++ for image analysis and electrophysiology) and I am trying to read H5 files storing recordings from 1024 micro-electrodes. These data are stored within an array of "int" with 1028 channels x many points (for ex 300,000) corresponding to the duration of the observation (data are sampled at 20 kHz)).
I would like to extract 1 channel at a time from this array using the hyperslabs approach.

It looks to me that it would be useful to add a ToArray1D as follow:

public static unsafe T[] ToArray1D(this T[] data, long dim0)
where T : unmanaged
{
var dims = new long[] { dim0 };
ArrayExtensions.ValidateInputData(data, dims);
var output = new T[dims[0]];
fixed (void* ptr = output)
{
ArrayExtensions.CopyData(data, ptr);
}
return output;
}

Is there any other way to do this? Right now, I resolved to use ToArray2D but it seems awkward.

Thank you for any help,

Frederic

PS By the way, for a beginner like me, HDF5.NET is the most understandable library and it makes it easy to read all other fields in the H5 file I am working on. Thumbs up for your work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FApollo3zehn%2FHDF5.NET%2Fissues%2F13&data=04%7C01%7C%7Cbb3b174c971541cc63e008d961c72593%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648330215065773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kp4w943roXQNaAxkr1G2PGni76%2Fmakg9F03yLBf3yFk%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFAAEYN3ZDVARVA2UE5WXM3T5LI7XANCNFSM5CKW7ZBA&data=04%7C01%7C%7Cbb3b174c971541cc63e008d961c72593%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648330215065773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0N2Sx%2B87JlMjtYe8%2ByxU9OyfCKr%2BALRs%2B%2FbEztXPJHM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cbb3b174c971541cc63e008d961c72593%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648330215075732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FCF8obb%2FfjicIMzisDWmKs8wCjewJAKY04p4wnrljUM%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cbb3b174c971541cc63e008d961c72593%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648330215075732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KFMDxROs%2BkfCZVmJImOprDotOKQ6IlfuKytEXor6Nkw%3D&reserved=0>.

**Comment by Apollo3zehn** [comment]
Hi Frederic,

just a small hint: you could replace "dataset.Space.Dimensions.Length" by "dataset.Space.Rank".

I am not sure why you need the "ToArray1D" method. With the hyperslab you are already getting a 1D result, don't you?

Your data have not been gzipped by the HDF library at the time of writing the data to file, otherwise you would have gotten an error when reading the data back again. This is because in the HDF file, the applied compression filters are documented. But it is possible that the data are gzipped before they have been passed over to the writing HDF lib.

Best regards,
Vincent



________________________________
Von: Frederic Marion-Poll ***@***.***>
Gesendet: Mittwoch, 18. August 2021 09:37
An: Apollo3zehn/HDF5.NET ***@***.***>
Cc: Apollo3zehn ***@***.***>; Comment ***@***.***>
Betreff: Re: [Apollo3zehn/HDF5.NET] ToArray1D: useful? (#13)


Thank you for your help, Vincent!

I have implemented the ToArray1D and I can read data with the following code from my file. I still don't know if it works, because (1) the data are Gzipped, and I don't know yet if I have to add a filter and (2) the data are stored as 10 bits int and I don't know if I have to apply a mask. But I get an array of int with the code below.

Again, bravo for your coding!
Fred

________________________________

public static int [] ReadAllElectrodeDataAsInt(int ElectrodeNumber)
{
int[] result;
try
{
H5Group group = Root.Group("/");
H5Dataset dataset = group.Dataset("sig");

            int ndimensions = dataset.Space.Dimensions.Length;
            if (ndimensions != 2)
                return null;
            ulong nbchannels = dataset.Space.Dimensions[0]; // 1028 expected
            ulong nbdatapoints = dataset.Space.Dimensions[1]; // any size - currently about 300 000
            var dataType = dataset.Type;

            var memoryDims = new ulong[] { nbdatapoints };

            var datasetSelection = new HyperslabSelection(
                rank: 2,
                starts: new ulong[] { (ulong)ElectrodeNumber, 0 },      // start at row ElectrodeNumber, column 0
                strides: new ulong[] { 1, 1 },                          // don't skip anything
                counts: new ulong[] { 1, nbdatapoints },                // read 1 row, ndatapoints columns
                blocks: new ulong[] { 1, 1 }                            // blocks are single elements
            );

            var memorySelection = new HyperslabSelection(
                rank: 1,
                starts: new ulong[] { 0 },
                strides: new ulong[] { 1 },
                counts: new ulong[] { nbdatapoints },
                blocks: new ulong[] { 1 }
            );

            result = dataset
                .Read<int>(
                    fileSelection: datasetSelection,
                    memorySelection: memorySelection,
                    memoryDims: memoryDims
                )
                .ToArray1D((long)nbdatapoints);

        }
        finally
        {
        }
        return result;
    }


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FApollo3zehn%2FHDF5.NET%2Fissues%2F13%23issuecomment-900890858&data=04%7C01%7C%7C1090b3dbfbd244fc936508d9621afc2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648690300077856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QiER58esJ8ug6ufOab0Xzsj0bxzMlZjhcVrKQF8WEJk%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFAAEYPDFEZY2FVOTQS5VYLT5NPKJANCNFSM5CKW7ZBA&data=04%7C01%7C%7C1090b3dbfbd244fc936508d9621afc2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648690300077856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SKCG1Qw1B26IOS1NiYBxHrnervbBu80q7SbjOpAJqvA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1090b3dbfbd244fc936508d9621afc2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648690300077856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lqnbo4pIZC8LUulcJjJg1qrx7xkZyKA%2FodPK%2FoG%2FNUw%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C1090b3dbfbd244fc936508d9621afc2d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648690300087808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HAkhSeGSVaIKrVsFhV38nNIjzQVl8ql2rwCs5daORkc%3D&reserved=0>.

**Comment by fmarionpoll** [comment]
Thank you, Vincent! indeed, I don't need ArrayTo1D! and I did not realize that "Rank" was there with the info I needed!
Reading 1 row of data takes ages as the file is 2 Gb. I seem to have read that it might be possible to read chunks in parallel. But for the moment, it seems to work indeed. 

As for the Gzip, you are probably right. However, when I look at the data file I use as a sample with hdfview.bat (calling a java program from HDF), I see "Compression: 2.851:1 GZIP: level=1"; "Fillter: GZIP" and "Storage Layout: CHUNKED: 1028x200". 

From your comments, I understand I should have got an error when reading such data without applying a filter?

Anyway, thank you so much for your help so far.

Best,
Fred

**Comment by Apollo3zehn** [comment]
I have not yet done performance tests with hyperslabs. Does it get faster if you switch the meaning of counts and blocks? (you then also need to adjust the stride parameter)

I.e.:

from

  strides: new ulong[] { 1, 1 },
  counts: new ulong[] { 1, nbdatapoints },
  blocks: new ulong[] { 1, 1 } //

to

  strides: new ulong[] { 1, nbdatapoints   },
  counts: new ulong[] { 1, 1},
  blocks: new ulong[] { 1, nbdatapoints  }

?

I am not sure if that will change anything but you could give it a try. If it is still slower than expected, it could be caused by bad sized chunks which would lead to many copy operations.

I have tested your current setup with the internal HyperslabUtils.Walk method, trying to read the fourth row (start = 3). This leads to a total of 1500 copy operation:

var datasetSelection = new HyperslabSelection(
    rank: 2,
    starts: new ulong[] { 3, 0 },
    strides: new ulong[] { 1, 1 },
    counts: new ulong[] { 1, 300000 },
    blocks: new ulong[] { 1, 1 }
);

var count = HyperslabUtils.Walk(2, dims: new[] { 1028UL, 300000UL }, chunkDims: new[] { 1028UL, 200UL }, datasetSelection).ToList().Count;

Output: count = 1500
I think that is not optimal but also not dramatic.

Built-in support for parallel read is not implemented yet. To safely do that the metadata cache of HDF5.NET must be thread-safe. I think I have not done it yet.

Regarding GZIP: When HDF View tells you so, it must be true. I think the confusion come from the fact that zlib, deflate and gzip are synonyms. So if H5Py is right (h5py/filters.py at master · h5py/h5py · GitHub<https://github.com/h5py/h5py/blob/master/h5py/_hl/filters.py#L14-L15>), gzip means actually "deflate" and that filter is aready built in by HDF5.NET (HDF5.NET/H5Filter.cs at master · Apollo3zehn/HDF5.NET · GitHub<https://github.com/Apollo3zehn/HDF5.NET/blob/master/src/HDF5.NET/Filters/H5Filter.cs#L164>). So your data are already decompressed and no error occurs 🙂

Best regards,
Vincent



________________________________
Von: Frederic Marion-Poll ***@***.***>
Gesendet: Mittwoch, 18. August 2021 12:51
An: Apollo3zehn/HDF5.NET ***@***.***>
Cc: Apollo3zehn ***@***.***>; Comment ***@***.***>
Betreff: Re: [Apollo3zehn/HDF5.NET] ToArray1D: useful? (#13)


Thank you, Vincent! indeed, I don't need ArrayTo1D! and I did not realize that "Rank" was there with the info I needed!
Reading 1 row of data takes ages as the file is 2 Gb. I seem to have read that it might be possible to read chunks in parallel. But for the moment, it seems to work indeed.

As for the Gzip, you are probably right. However, when I look at the data file I use as a sample with hdfview.bat (calling a java program from HDF), I see "Compression: 2.851:1 GZIP: level=1"; "Fillter: GZIP" and "Storage Layout: CHUNKED: 1028x200".

From your comments, I understand I should have got an error when reading such data without applying a filter?

Anyway, thank you so much for your help so far.

Best,
Fred

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FApollo3zehn%2FHDF5.NET%2Fissues%2F13%23issuecomment-901014880&data=04%7C01%7C%7C16c271b4a9bc4be93b8008d9623621ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648806898757967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pAMO84BF7lfdez5p%2FNpKdw7Ygqsh9MEExgyydXaaM4M%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFAAEYKBB2CJUWCXITQLJPDT5OGDBANCNFSM5CKW7ZBA&data=04%7C01%7C%7C16c271b4a9bc4be93b8008d9623621ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648806898757967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CE6Nam8Tdg1idtnV%2FmQtSEkxNpk%2FX74n5j2phT9dxCg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C16c271b4a9bc4be93b8008d9623621ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648806898767917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NeGdBx6NS190SqYsYVnjbb84LxPcy2CmPzvRfimU1p0%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C16c271b4a9bc4be93b8008d9623621ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648806898767917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i87jPT4ODpn4S7pXZvzQU4Vn7XjN05qmYslwXiqphOY%3D&reserved=0>.

**Comment by fmarionpoll** [comment]
Thank you, Vincent. 

 

If you want to check other things on this particular data file, here is a link (valid a week or so):

https://filesender.renater.fr/?s=download <https://filesender.renater.fr/?s=download&token=e9ddbd31-17ec-425c-a182-0b8c1e10b7e9> &token=e9ddbd31-17ec-425c-a182-0b8c1e10b7e9

 

 

I’ll test what you suggest and will post it later.

 

Best regards,

Fred

**Comment by fmarionpoll** [comment]
Ok, I did what you suggest by replacing the data selection parameters.

The original time was: 27007 ms

The new time was: 26833 ms

 

The difference between the 2 strategies look negligible.

 

Best,

Fred

**Comment by Apollo3zehn** [comment]
Thank for the file, I'll check it tomorrow morning.

**Comment by fmarionpoll** [comment]
The format of sig data is probably ushort and not int, as data are coded on 10 bits. If I read the sig buffer with int, I get half the number of points declared in the H5 array; with ushort, it is ok.

**Comment by fmarionpoll** [comment]
Thank you, Vincent.

I'll have look.

As for the site of the Chunk and the idea of reading a point under 10 for ex, this will not do as the relevant information in these recordings is the occurrence of action potentials. Each event (spike), is 2 ms long, so there not much room for undersampling.  As you suggested, the most straightforward thing to do would be to divide the work in threads.I tried to read the whole data and keep it in memory but it was not accepted by the debugger (1028 x 3 000 000 16 bits words is a lot).

One way to go would be to store a reduced "image" of all data so that we could display quickly any channel at the current chosen screen resolution and time intervals to avoid re-reading the whole data each time.Again, thank you for your help, ideas, and most of it, for HD5.NETalpha!Fred
From my phone
