### ISSUE TITLE
how to traverse the attributes of a group or a dataset?

### ISSUE THREAD

**Issue by Fokatu** [Apollo3zehn/HDF5.NET#21]
traverse the attributes  and show the corresponding contents.
Thanks

**Comment by Apollo3zehn** [comment]
Groups and datasets have the property
`public IEnumerable<H5Attribute> Attributes`

You can iterate using the IEnumerable and then read the contents of each attribute using the `Read<T>()` method.

**Comment by Fokatu** [comment]
Thanks for your reply. My question is how to get the type of the attribute, i.e., the T for the function Read？

**Comment by Fokatu** [comment]
![image](https://user-images.githubusercontent.com/25919117/141826756-5ac4b168-ac90-4567-bf14-1dfeb13ba3e4.png)
How to implement the above table?

**Comment by Apollo3zehn** [comment]
To read a structure / compound, you could create a type that maps to the one in the HDF file: https://github.com/Apollo3zehn/HDF5.NET#structs-with-nullable-fields

To get the data type of an attribute, there is the `Type` property. This gives you the type class but currently no further information. I have to expose more details to make that property useful. That's why its still an alpha stage project :-)

**Comment by Fokatu** [comment]
Do you mean that I cannot implement the function shown in the above image for arbitrary hdf5 file?

**Comment by Apollo3zehn** [comment]
Yes, that is currently not possible. As a workaround you could clone the repo, make the DataTypeMessage property public and then implement your routine to read arbitrary structs. Here is a PR witch tries to solve the same problem: https://github.com/Apollo3zehn/HDF5.NET/pull/15

I will need some time to implement a proper solution to read arbitrary HDF5 structs. Until then the only way is follow the approach of #15 .

**Comment by Apollo3zehn** [comment]
Reading unknown structs is now possible: https://github.com/Apollo3zehn/HDF5.NET#63-unknown-structs
