### ISSUE TITLE
NBit filter?

### ISSUE THREAD

**Issue by Xqua** [Apollo3zehn/HDF5.NET#22]
Hi,

I am trying to read data that was compressed with Gzip, but I am getting this error:

```
Exception: The filter 'Nbit' is not yet supported by HDF5.NET.
HDF5.NET.H5Filter.NbitFilterFunc (HDF5.NET.H5FilterFlags flags, System.UInt32[] parameters, System.Memory`1[T] buffer) (at <fb37093370234856bd3792f3c203654a>:0)
```

Could you help me/guide me towards getting this solved?

**Comment by Xqua** [comment]
Also, HDFview says its Gzip too ?
![image](https://user-images.githubusercontent.com/1092155/145632347-dd55273d-1ce5-4741-8797-e753d12b400f.png)


But why dies HDF5.NET invokes Nbit ?

**Comment by Apollo3zehn** [comment]
HDFView also shows "SCALEOFFSET", I think this is the nbit filter (so your data are filtered with two different methods). I was not yet able to implement that nbit filter because I did not yet fully understand it (original code here: https://github.com/HDFGroup/hdf5/blob/develop/src/H5Znbit.c). To implement it, I need to find a generic way (for all data types) and even better would be a vectorized implementation to have good performance. But of course a simple implementation would be better than nothing. I'll try to find a solution next week.

**Comment by Xqua** [comment]
That would be amazing! Let me know if you do!

**Comment by Apollo3zehn** [comment]
I found that scale offset filter is really the scale offset filter and not nbit. There was an error in the invocation of the correct method. I have started implementing the scale offset filter today and I think I will have finished and publishd it on Friday.

**Comment by Apollo3zehn** [comment]
I have publish a new prerelease (https://www.nuget.org/packages/HDF5.NET/1.0.0-alpha.12.final) with the ScaleOffset filter included. I hope it works for you now :-)

**Comment by Xqua** [comment]
Nice I'll try it next week !
