### ISSUE TITLE
[Question] reading dynamic compound dataset

### ISSUE THREAD

**Issue by LiorBanai** [Apollo3zehn/HDF5.NET#3]
Hi,
I was wondering how to read back a compound dataset from existing H5 file without knowing its strucutre (even read it as dictionary of <string,object> is ok) or reading the columns separately.

Do you have example by any chance in your library?

**Comment by Marco-Pellegrino** [comment]
Follow

**Comment by Apollo3zehn** [comment]
@LiorBanai sorry I die not get any notification for this issue. I check that later today.

Right now there is a bug when reading multidimensional chunked arrays because I got the chunking idea wrong. But I found a solution to this and the general hyperslab problem. I'll try to push an update next week.

**Comment by Apollo3zehn** [comment]
It have in mind a few options:

- create new type using reflection
Parse the HDF struct definition and create a matching type for it. But i think its useless for the user because he can then access data only via reflection. Supports child structs.

- Dictionary<string, byte[]>
This would read all content into a raw byte array. Easy to implement, difficult to use. No support for child structs.

- Dictionary<string, object>
This allows reading a hierarchy of objects, i.e. child structs are no problem. "Object" will always be a primitive type or a string (like a JSON file). I think boolean would not be an option, that would require to convert the HDF5 bit field and I would like to keep the lib as straightforward as possible. Maybe this could be part of an extension method.

- ExpandoObject

ExpandoObject behaves like a `Dictionary<string, object>`
:
```cs
var a = new ExpandoObject();
a.TryAdd("key", 123123);
var b = ((IDictionary<string, object>)a)["key"];
```

And when the user wants dynamic access, he can install the System.Dynamic dependency and do:
```cs
dynamic a = new ExpandoObject();
var b = a.key;
```

I think ExpandoObject this is actually the best option (I guess you already had it in mind when asking this question).

I will add support for this, probably in the form of "IDictionary<string, object> ReadDynamicCompound()". Please keep in mind that this method will not be the fastest as it needs to construct many objects (depending on the HDF5 file). But for simple use cases this should be sufficient.

**Comment by LiorBanai** [comment]
Yeah, ExpandoObject/IDictionary<string, object> sounds great.  Also since this method will be (when reading root File and below) costly a less performant flow is a given :)

**Comment by Apollo3zehn** [comment]
Closed in favor of #9.

**Comment by Apollo3zehn** [comment]
@LiorBanai , HDF5.NET (v1.0.0-alpha.19) now supports reading unknown structs as `Dictionary<string, object>`. I decided to not use the `ExpandoObject` approach since it requires the dynamic CLR to be added as a dependency which is too uncommon and intrusive I think. I think `Dictionary<string, object>` covers everything the user needs.

**Comment by LiorBanai** [comment]
Thanks! I'll check it out
